### ISSUE TITLE
SRS ist nicht fertig

### ISSUE THREAD

**Issue by einBuegelbrett** [NikomitK/TINF22F_Team3_ECAD_Topology_Editor#68]
![image](https://github.com/NikomitK/TINF22F_Team3_ECAD_Topology_Editor/assets/102304412/c76f074c-fe77-4c92-8428-196595cceb7c)

**Comment by A2i2C** [comment]
Wie da steht, check with developer Team, müsste mit entweder Niko, Simon, Alex oder allem 3 ein Gespräch führen, um dies dementsprechend zu ändern.
